# Site settings
title: Oddacious
header-img: img/barbados.jpg
email: fumble.to.victory@gmail.com
description: "Collecting my notes on sports analytics and other assorted topics"
baseurl: ""
url: https://oddacious.github.io
#host: 0.0.0.0
twitter_username: gentleputsch
github_username: 
facebook_username:
share_enabled: 1


# Build settings
markdown: kramdown
highlighter: pygments
#permalink: pretty
permalink: /:title
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","mail","contact.html"]
include: [".htaccess"]

gems:
    - jekyll-sitemap

